#pragma once
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <cmath>
#include <algorithm>
#include <iomanip>
#include <functional>
#include <vector>
#include "core/global.hpp"
#include "simplex/simplex.hpp"